// Shared placeholder content for Choi Juhwan's portfolio
window.PORTFOLIO_DATA = {
  name: "CHOI JUHWAN",
  handle: "@juhwan_eth",
  role: "Independent researcher & builder",
  bio: "Researching restaking, intent architectures, and the economic surface of L2s. Building tooling for onchain analysts. Previously infra @ a stealth L1, before that a quant intern who learned Solidity on the train.",
  location: "Seoul / remote",
  email: "juhwan@protonmail.com",
  socials: [
    { label: "GITHUB",    handle: "github.com/juhwan",         url: "#" },
    { label: "X",         handle: "x.com/juhwan_eth",          url: "#" },
    { label: "MIRROR",    handle: "mirror.xyz/juhwan.eth",     url: "#" },
    { label: "FARCASTER", handle: "warpcast.com/juhwan",       url: "#" },
    { label: "EMAIL",     handle: "juhwan@protonmail.com",     url: "#" },
  ],
  now: [
    "Writing a long piece on LRT depegs after the Renzo episode.",
    "Shipping v0.4 of MEVSCOPE — adding Base + Blast support.",
    "Reading: 'Flash Boys 2.0', 'The Sovereign Individual'.",
    "Open to chat about: intent solvers, restaking risk, AVS economics.",
  ],
  posts: [
    {
      id: "lrt-depeg-anatomy",
      date: "2026.05.04",
      tag: "RESEARCH",
      readtime: "14 MIN",
      title: "Anatomy of an LRT depeg",
      dek: "What actually happens in the eight hours after a liquid restaking token loses its anchor — withdrawal queues, AMM curves, and the social layer.",
      stats: { views: "12.4k", mirrors: "1.1k", comments: "84" },
    },
    {
      id: "intents-not-orders",
      date: "2026.04.18",
      tag: "THESIS",
      readtime: "9 MIN",
      title: "Intents are not orders",
      dek: "Why the intent-centric framing is more than a UX trick — and what it implies for solver markets, MEV, and the role of the wallet.",
      stats: { views: "8.7k", mirrors: "642", comments: "51" },
    },
    {
      id: "avs-economics-101",
      date: "2026.03.27",
      tag: "PRIMER",
      readtime: "22 MIN",
      title: "AVS economics, from first principles",
      dek: "A working model for how an actively validated service prices security, why most current AVSes are mispriced, and what a fair rent looks like.",
      stats: { views: "21.2k", mirrors: "2.4k", comments: "162" },
    },
    {
      id: "points-are-debt",
      date: "2026.02.11",
      tag: "OPINION",
      readtime: "6 MIN",
      title: "Points are debt",
      dek: "Every points program is an unfunded liability. A short note on why the second-order effects are worse than people think.",
      stats: { views: "33.0k", mirrors: "3.9k", comments: "247" },
    },
    {
      id: "solana-mev-notes",
      date: "2026.01.22",
      tag: "FIELD NOTES",
      readtime: "11 MIN",
      title: "Solana MEV — six months in the mempool",
      dek: "Numbers, screenshots, and unanswered questions from running a Jito-style searcher on mainnet through Q1.",
      stats: { views: "15.6k", mirrors: "1.3k", comments: "94" },
    },
  ],
  projects: [
    {
      name: "MEVSCOPE",
      status: "SHIPPING",
      version: "v0.4.1",
      url: "mevscope.xyz",
      summary: "Real-time MEV explorer. Tags every block on Ethereum, Base, and Arbitrum with sandwich, arb, and liquidation flow.",
      stack: ["RUST", "POSTGRES", "REVM", "NEXT"],
      metric: { label: "BLOCKS / DAY", value: "1.2M" },
    },
    {
      name: "LRT-DASH",
      status: "LIVE",
      version: "v1.0",
      url: "lrt-dash.eth.limo",
      summary: "Liquid restaking dashboard. Tracks peg, withdrawal queue depth, and AVS exposure across 14 LRT issuers.",
      stack: ["TS", "VIEM", "DUNE", "SVELTE"],
      metric: { label: "TVL TRACKED", value: "$8.4B" },
    },
    {
      name: "RESTAKEKIT",
      status: "BUILDING",
      version: "v0.1-α",
      url: "github.com/juhwan/restakekit",
      summary: "Typed SDK for interacting with the major restaking protocols. One interface, every AVS.",
      stack: ["TS", "VIEM", "ZOD"],
      metric: { label: "AVS COVERED", value: "27" },
    },
    {
      name: "ONCHAIN-REP",
      status: "LIVE",
      version: "v2.1",
      url: "onchain-rep.xyz",
      summary: "Reputation graph for EVM addresses. Powers a small but growing set of underwriting tools.",
      stack: ["GO", "NEO4J", "FOUNDRY"],
      metric: { label: "ADDRESSES", value: "11.7M" },
    },
    {
      name: "TX-DIFF",
      status: "ARCHIVED",
      version: "v0.3",
      url: "github.com/juhwan/tx-diff",
      summary: "Compare two transaction simulations side by side. Useful for audits, abandoned for lack of time.",
      stack: ["PYTHON", "FOUNDRY"],
      metric: { label: "FORKS", value: "412" },
    },
  ],
  experience: [
    { period: "2024 — NOW",   org: "INDEPENDENT",      role: "Researcher & builder",       note: "Self-funded. Writing, shipping tools, occasional consulting." },
    { period: "2023 — 2024",  org: "STEALTH L1",        role: "Protocol engineer",          note: "Worked on consensus tooling and a fee market redesign. NDA." },
    { period: "2022 — 2023",  org: "BLOCKHOUSE CAPITAL", role: "Quant intern → analyst",     note: "Built the firm's first on-chain data pipeline. Mostly Dune, eventually Rust." },
    { period: "2020 — 2022",  org: "SNU CSE",           role: "BSc, Computer Science",      note: "Thesis on adversarial robustness. Wrote my first contract sophomore year." },
  ],
};
